---
language: go
go:
- 1.14
- 1.15

services:
- redis-server
- mysql

install:
- go get github.com/c9s/rockhopper/cmd/rockhopper

before_script:
- go mod download
script:
- bash scripts/test-sqlite3-migrations.sh
- go test -v ./pkg/...
