---
language: go
go:
- 1.14
- 1.15
services:
- redis-server
before_script:
- go get github.com/c9s/rockhopper
- go mod download
script:
- bash scripts/test-sqlite3-migrations.sh
- go test -v ./pkg/...
