---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bbgo.fullname" . }}
  labels:
    {{- include "bbgo.labels" . | nindent 4 }}
data:
  bbgo.yaml: |-
    {{- .Files.Get .Values.configmap.file | nindent 4 }}
