---
imports:
- github.com/c9s/bbgo/pkg/strategy/buyandhold
- github.com/c9s/bbgo/pkg/strategy/xpuremaker

notifications:
  slack:
    defaultChannel: "bbgo"
    errorChannel: "bbgo-error"

reportTrades:
  channelBySymbol:
    "btcusdt": "bbgo-btcusdt"
    "ethusdt": "bbgo-ethusdt"
    "bnbusdt": "bbgo-bnbusdt"
    "sxpusdt": "bbgo-sxpusdt"
    "maxusdt": "max-maxusdt"

reportPnL:
- averageCostBySymbols:
  - "BTCUSDT"
  - "BNBUSDT"
  of: binance
  when:
  - "@daily"
  - "@hourly"

sessions:
  max:
    exchange: max
    envVarPrefix: max
    orderExecutor:
      bySymbol:
        BTCUSDT:
          RiskControlOrderExecutor:
            minQuoteBalance: 1000.0
            maxBaseAssetBalance: 10.0
            minBaseAssetBalance: 1.0
            maxOrderAmount: 100.0

  binance:
    exchange: binance
    envVarPrefix: binance

exchangeStrategies:
- on: binance
  buyandhold:
    symbol: "BTCUSDT"
    interval: "1m"
    baseQuantity: 0.01
    minDropPercentage: -0.02
- on: max
  xpuremaker:
    symbol: MAXUSDT
    numOrders: 2
    side: both
    behindVolume: 1000.0
    priceTick: 0.01
    baseQuantity: 100.0
