---
notifications:
  slack:
    defaultChannel: "bbgo"
    errorChannel: "bbgo-error"

reportTrades:
  channelBySymbol:
    "btcusdt": "bbgo-btcusdt"
    "ethusdt": "bbgo-ethusdt"
    "bnbusdt": "bbgo-bnbusdt"
    "sxpusdt": "bbgo-sxpusdt"

reportPnL:
  - averageCostBySymbols:
      - "BTCUSDT"
      - "BNBUSDT"
    of: binance
    when:
      - "@daily"
      - "@hourly"

sessions:
  max:
    exchange: max
    keyVar: MAX_API_KEY
    secretVar: MAX_API_SECRET
  binance:
    exchange: binance
    keyVar: BINANCE_API_KEY
    secretVar: BINANCE_API_SECRET

exchangeStrategies:
  - on: binance
    buyandhold:
      symbol: "BTCUSDT"
      interval: "1m"
      baseQuantity: 0.01
      minDropPercentage: -0.02
