---
notifications:
  slack:
    defaultChannel: "dev-bbgo"
    errorChannel: "bbgo-error"

  # if you want to route channel by symbol
  symbolChannels:
    "^BTC": "btc"
    "^ETH": "eth"

  # if you want to route channel by exchange session
  sessionChannels:
    max: "bbgo-max"
    binance: "bbgo-binance"

  # routing rules
  routing:
    trade: "$symbol"
    order: "$symbol"
    submitOrder: "$session"
    pnL: "bbgo-pnl"

reportPnL:
- averageCostBySymbols:
  - "BTCUSDT"
  - "BNBUSDT"
  of: binance
  when:
  - "@daily"
  - "@hourly"

sessions:
  max:
    exchange: max
    envVarPrefix: max

backtest:
  # for testing max draw down (MDD) at 03-12
  # see here for more details
  # https://www.investopedia.com/terms/m/maximum-drawdown-mdd.asp
  startTime: "2020-01-01"
  endTime: "2020-01-15"
  symbols:
  - BTCUSDT
  account:
    makerCommission: 15
    takerCommission: 15
    buyerCommission: 0
    sellerCommission: 0
    balances:
      BTC: 0.0
      USDT: 10000.0

exchangeStrategies:

- on: max
  buyandhold:
    symbol: "BTCUSDT"
    interval: "5m"
    baseQuantity: 0.01
    # minDropPercentage: 0.01
    minDropChange: 100.0

- on: max
  grid:
    symbol: BTCUSDT
    quantity: 0.001
    gridNumber: 100
    profitSpread: 50.0
    upperPrice: 30000.0
    lowerPrice: 10000.0

