---
persistence:
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

# example command:
#    godotenv -f .env.local -- go run ./cmd/bbgo backtest --exchange max --sync-from 2020-11-01 --config config/grid.yaml --base-asset-baseline
backtest:
  # for testing max draw down (MDD) at 03-12
  # see here for more details
  # https://www.investopedia.com/terms/m/maximum-drawdown-mdd.asp
  startTime: "2021-08-01"
  endTime: "2021-10-30"
  symbols:
  - ETHUSDT
  account:
    balances:
      ETH: 1.0
      USDT: 20_000.0

exchangeStrategies:

- on: max
  bollmaker:
    symbol: ETHUSDT
    interval: 5m
    quantity: 0.005

    # spread: sell price = middle price + spread, buy price = middle price - spread
    # you need to ensure that the spread can cover your trading fee
    # for example, the trading fee on binance is 0.075%, so the total fee of your buy/sell orders is 0.075% * 2 = 0.14%
    spread: 0.01%
    minProfitSpread: 0.1%

    defaultBollinger:
      interval: "5m"
      window: 21
      bandWidth: 2.0
    neutralBollinger:
      interval: "5m"
      window: 21
      bandWidth: 1.0

