---
notifications:
  slack:
    defaultChannel: "bbgo"
    errorChannel: "bbgo-error"

reportTrades:
  channelBySymbol:
    "btcusdt": "bbgo-btcusdt"
    "ethusdt": "bbgo-ethusdt"
    "bnbusdt": "bbgo-bnbusdt"

reportPnL:
- averageCostBySymbols:
  - "BTCUSDT"
  - "ETHUSDT"
  - "BNBUSDT"
  of: binance
  when:
  - "@daily"
  - "@hourly"

sessions:
  binance:
    exchange: binance
    envVarPrefix: binance

riskControls:
  # This is the session-based risk controller, which let you configure different risk controller by session.
  sessionBased:
    # "max" is the session name that you want to configure the risk control
    max:
      # orderExecutors is one of the risk control
      orderExecutors:
        # symbol-routed order executor
        bySymbol:
          BTCUSDT:
            # basic risk control order executor
            basic:
              minQuoteBalance: 1000.0
              maxBaseAssetBalance: 2.0
              minBaseAssetBalance: 0.1
              maxOrderAmount: 100.0

exchangeStrategies:
- on: binance
  buyandhold:
    symbol: "BTCUSDT"
    interval: "1m"
    baseQuantity: 0.001
    minDropPercentage: -0.0001
