---
backtest:
  startTime: "2023-06-01"
  endTime: "2023-07-01"
  sessions:
  - max
  symbols:
  - ETHUSDT
  accounts:
    binance:
      balances:
        USDT: 20_000.0

persistence:
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

exchangeStrategies:

- on: max
  dca2:
    symbol: ETHUSDT
    short: false
    budget: 200
    maxOrderNum: 5
    priceDeviation: 1%
    takeProfitRatio: 0.2%
    coolDownInterval: 3m
    circuitBreakLossThreshold: -0.9
