---
persistence:
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

sessions:
  binance:
    exchange: binance
    futures: false
    envVarPrefix: binance
    heikinAshi: false

    # Drift strategy intends to place buy/sell orders as much value mas it could be. To exchanges that requires to
    # calculate fees before placing limit orders (e.g. FTX Pro), make sure the fee rate is configured correctly and
    # enable modifyOrderAmountForFee to prevent order rejection.
    makerFeeRate: 0.0002
    takerFeeRate: 0.0007
    modifyOrderAmountForFee: false

exchangeStrategies:
 
- on: binance
  drift:
    canvasPath: "./output.png"
    symbol: ETHBUSD
    # kline interval for indicators
    interval: 15m
    window: 2
    stoploss: 0.3%
    source: close
    predictOffset: 2
    # the init value of takeProfitFactor Series, position avg +- takeProfitFactor * atr as take profit price
    takeProfitFactor: 6
    profitFactorWindow: 8
    noTrailingStopLoss: false
    # stddev on high/low-source
    hlVarianceMultiplier: 0.22
    hlRangeWindow: 5
    smootherWindow: 2
    fisherTransformWindow: 8
    atrWindow: 14

    generateGraph: true
    graphPNLDeductFee: true
    graphPNLPath: "./pnl.png"
    graphCumPNLPath: "./cumpnl.png"
    #exits:
    #- roiStopLoss:
    #   percentage: 0.8%
    #- roiTakeProfit:
    #   percentage: 35%
    #- protectiveStopLoss:
    #   activationRatio: 0.6%
    #   stopLossRatio: 0.1%
    #   placeStopOrder: false
    #- protectiveStopLoss:
    #   activationRatio: 5%
    #   stopLossRatio: 1%
    #   placeStopOrder: false
    #- cumulatedVolumeTakeProfit:
    #   interval: 5m
    #   window: 2
    #   minQuoteVolume: 200_000_000
    #- protectiveStopLoss:
    #    activationRatio: 2%
    #    stopLossRatio: 1%
    #    placeStopOrder: false

sync:
  userDataStream:
    trades: true
    filledOrders: true
  sessions:
    - binance
  symbols:
    - ETHBUSD

backtest:
  startTime: "2022-01-01"
  endTime: "2022-07-29"
  symbols:
    - ETHBUSD
  sessions: [binance]
  accounts:
    binance:
      makerFeeRate: 0.0000
      #takerFeeRate: 0.00001
      balances:
        ETH: 10
        BUSD: 5000.0
