---
sessions:
  binance:
    exchange: binance
    futures: true
    envVarPrefix: binance
    heikinAshi: false

exchangeStrategies:
 
- on: binance
  drift:
    symbol: ETHUSDT
    # kline interval for indicators
    interval: 15m
    window: 3
    exits:
    - roiStopLoss:
       percentage: 0.8%
    - roiTakeProfit:
       percentage: 35%
    - protectiveStopLoss:
       activationRatio: 0.6%
       stopLossRatio: 0.1%
       placeStopOrder: false
    - protectiveStopLoss:
       activationRatio: 5%
       stopLossRatio: 1%
       placeStopOrder: false
    - cumulatedVolumeTakeProfit:
       interval: 5m
       window: 2
       minQuoteVolume: 200_000_000
    #- protectiveStopLoss:
    #    activationRatio: 2%
    #    stopLossRatio: 1%
    #    placeStopOrder: false

sync:
  userDataStream:
    trades: true
    filledOrders: true
  sessions:
    - binance
  symbols:
    - ETHUSDT

backtest:
  startTime: "2022-04-01"
  endTime: "2022-06-18"
  symbols:
    - ETHUSDT
  sessions: [binance]
  accounts:
    binance:
      #makerFeeRate: 0
      #takerFeeRate: 0
      balances:
        ETH: 0.0
        USDT: 5000.0
