---
persistence:
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

sessions:
  binance:
    exchange: binance
    futures: false
    envVarPrefix: binance
    heikinAshi: false

    # Drift strategy intends to place buy/sell orders as much value mas it could be. To exchanges that requires to
    # calculate fees before placing limit orders (e.g. FTX Pro), make sure the fee rate is configured correctly and
    # enable modifyOrderAmountForFee to prevent order rejection.
    makerFeeRate: 0.0002
    takerFeeRate: 0.0007
    modifyOrderAmountForFee: false

exchangeStrategies:
 
- on: binance
  drift:
    canvasPath: "./output.png"
    symbol: ETHBUSD
    limitOrder: false
    quantity: 0.01
    # kline interval for indicators
    interval: 1m
    window: 1
    useAtr: true
    useStopLoss: true
    stoploss: 0.23%
    source: ohlc4
    predictOffset: 2
    noTrailingStopLoss: false
    trailingStopLossType: kline
    # stddev on high/low-source
    hlVarianceMultiplier: 0.13
    hlRangeWindow: 4
    smootherWindow: 19
    fisherTransformWindow: 73
    atrWindow: 14
    # orders not been traded will be canceled after `pendingMinutes` minutes
    pendingMinutes: 5
    noRebalance: true
    trendWindow: 12
    rebalanceFilter: 2

    trailingActivationRatio: [0.0015, 0.002, 0.004, 0.01]
    trailingCallbackRate: [0.0001, 0.00012, 0.001, 0.002]

    generateGraph: true
    graphPNLDeductFee: true
    graphPNLPath: "./pnl.png"
    graphCumPNLPath: "./cumpnl.png"
    #exits:
    #- roiStopLoss:
    #   percentage: 0.8%
    #- roiTakeProfit:
    #   percentage: 35%
    #- protectiveStopLoss:
    #   activationRatio: 0.6%
    #   stopLossRatio: 0.1%
    #   placeStopOrder: false
    #- protectiveStopLoss:
    #   activationRatio: 5%
    #   stopLossRatio: 1%
    #   placeStopOrder: false
    #- cumulatedVolumeTakeProfit:
    #   interval: 5m
    #   window: 2
    #   minQuoteVolume: 200_000_000
    #- protectiveStopLoss:
    #    activationRatio: 2%
    #    stopLossRatio: 1%
    #    placeStopOrder: false

sync:
  userDataStream:
    trades: true
    filledOrders: true
  sessions:
    - binance
  symbols:
    - ETHBUSD

backtest:
  startTime: "2022-09-25"
  endTime: "2022-09-30"
  symbols:
    - ETHBUSD
  sessions: [binance]
  accounts:
    binance:
      makerFeeRate: 0.0000
      takerFeeRate: 0.0000
      balances:
        ETH: 0.03
        BUSD: 0
