---
sessions:
  binance:
    exchange: binance
    envVarPrefix: binance

exchangeStrategies:
 
- on: binance
  ewo_dgtrd:
    symbol: MATICUSDT
    interval: 15m
    threshold: 0.9
    useEma: true
    sigWin: 5
    stoploss: 2%

backtest:
  startTime: "2022-04-09"
  endTime: "2022-04-13"
  symbols:
    - MATICUSDT
  sessions: [binance]
  account:
    binance:
      balances:
        MATIC: 0
        USDT: 10000
