---
sessions:
  binance:
    exchange: binance
    envVarPrefix: binance

exchangeStrategies:
 
- on: binance
  ewo_dgtrd:
    symbol: MATICUSDT
    interval: 30m
    useEma: true
    sigWin: 3
    stops:
    - trailingStop:
        callbackRate: 5.1%
        closePosition: 20%
        minProfit: 2%
        interval: 1m
        virtual: true

backtest:
  startTime: "2022-03-03"
  endTime: "2022-04-13"
  symbols:
    - MATICUSDT
  sessions: [binance]
  account:
    binance:
      balances:
        MATIC: 0
        USDT: 10000
