---
sessions:
  binance:
    exchange: binance
    envVarPrefix: binance

exchangeStrategies:
 
- on: binance
  ewo_dgtrd:
    symbol: MATICUSDT
    interval: 1h
    threshold: 13
    useEma: true
    sigWin: 5
    stoploss: 2%

backtest:
  startTime: "2022-03-01"
  endTime: "2022-04-10"
  symbols:
    - MATICUSDT
  account:
    binance:
      balances:
        MATIC: 0
        USDT: 10000
