---
sessions:
  binance:
    exchange: binance
    futures: true
    envVarPrefix: binance

exchangeStrategies:
 
- on: binance
  ewo_dgtrd:
    symbol: MATICUSDT
    interval: 2h
    useEma: false
    useSma: false
    sigWin: 8
    stoploss: 10%
    useHeikinAshi: true
    disableShortStop: false
    #stops:
    #- trailingStop:
    #    callbackRate: 5.1%
    #    closePosition: 20%
    #    minProfit: 1%
    #    interval: 1m
    #    virtual: true

sync:
  userDataStream:
    trades: true
    filledOrders: true
  sessions:
    - binance
  symbols:
    - MATICUSDT

backtest:
  startTime: "2022-05-01"
  endTime: "2022-05-11"
  symbols:
    - MATICUSDT
  sessions: [binance]
  accounts:
    binance:
      #makerFeeRate: 0
      #takerFeeRate: 15
      balances:
        MATIC: 5000.0
        USDT: 10000
