---
sessions:
  binance:
    exchange: binance
    futures: true
    envVarPrefix: binance

exchangeStrategies:
 
- on: binance
  ewo_dgtrd:
    symbol: MATICUSDT
    # kline interval for indicators
    interval: 2h
    # use ema as MA
    useEma: false
    # use sma as MA, used when ema is false
    # if both sma and ema are false, use EVMA
    useSma: false
    # ewo signal line window size
    sigWin: 8
    # SL percentage from entry price
    stoploss: 15%
    # use HeikinAshi klines instead of normal OHLC
    useHeikinAshi: true
    # disable SL when short
    disableShortStop: false
    # CCI Stochastic Indicator high filter
    ccistochFilterHigh: 80
    # CCI Stochastic Indicator low filter
    ccistochFilterLow: 20

sync:
  userDataStream:
    trades: true
    filledOrders: true
  sessions:
    - binance
  symbols:
    - MATICUSDT

backtest:
  startTime: "2022-05-01"
  endTime: "2022-05-24"
  symbols:
    - MATICUSDT
  sessions: [binance]
  accounts:
    binance:
      #makerFeeRate: 0
      #takerFeeRate: 15
      balances:
        MATIC: 5000.0
        USDT: 10000
