---
sessions:
  binance:
    exchange: binance
    futures: true
    envVarPrefix: binance

exchangeStrategies:
 
- on: binance
  ewo_dgtrd:
    symbol: MATICUSDT
    interval: 30m
    useEma: false
    useSma: false
    sigWin: 3
    stoploss: 2%
    useHeikinAshi: true
    disableShortStop: true
    #stops:
    #- trailingStop:
    #    callbackRate: 5.1%
    #    closePosition: 20%
    #    minProfit: 1%
    #    interval: 1m
    #    virtual: true

sync:
  userDataStream:
    trades: true
    filledOrders: true
  sessions:
    - binance
  symbols:
    - MATICUSDT

backtest:
  startTime: "2022-04-14"
  endTime: "2022-04-28"
  symbols:
    - MATICUSDT
  sessions: [binance]
  account:
    binance:
      makerFeeRate: 0
      takerFeeRate: 0
      balances:
        MATIC: 500
        USDT: 10000
