---
sessions:
  max:
    exchange: max
    envVarPrefix: max

riskControls:
  # This is the session-based risk controller, which let you configure different risk controller by session.
  sessionBased:
    # "max" is the session name that you want to configure the risk control
    max:
      # orderExecutor is one of the risk control
      orderExecutor:
        # symbol-routed order executor
        bySymbol:
          USDTTWD:
            # basic risk control order executor
            basic:
              minQuoteBalance: 100.0  # keep 100 twd
              maxBaseAssetBalance: 1000.0
              minBaseAssetBalance: 200.0
              maxOrderAmount: 2000.0 # 1000 twd

backtest:
  # for testing max draw down (MDD) at 03-12
  # see here for more details
  # https://www.investopedia.com/terms/m/maximum-drawdown-mdd.asp
  startTime: "2020-09-04"
  endTime: "2020-09-14"
  symbols:
  - BTCUSDT
  - ETHUSDT
  - USDTTWD
  account:
    makerCommission: 15
    takerCommission: 15
    balances:
      BTC: 0.0
      USDT: 10000.0

exchangeStrategies:
- on: max
  grid:
    symbol: USDTTWD
    quantity: 10.0
    gridNumber: 50
    profitSpread: 0.1
    upperPrice: 28.50
    lowerPrice: 27.90
    long: true
