---
sessions:
  binance:
    exchange: binance
    envVarPrefix: binance

  max:
    exchange: max
    envVarPrefix: max

riskControls:
  # This is the session-based risk controller, which let you configure different risk controller by session.
  sessionBased:
    # "max" is the session name that you want to configure the risk control
    max:
      # orderExecutor is one of the risk control
      orderExecutor:
        # symbol-routed order executor
        bySymbol:
          BTCUSDT:
            # basic risk control order executor
            basic:
              minQuoteBalance: 100.0
              maxBaseAssetBalance: 3.0
              minBaseAssetBalance: 0.0
              maxOrderAmount: 1000.0

backtest:
  # for testing max draw down (MDD) at 03-12
  # see here for more details
  # https://www.investopedia.com/terms/m/maximum-drawdown-mdd.asp
  startTime: "2020-09-04"
  endTime: "2020-09-14"
  symbols:
  - BTCUSDT
  - ETHUSDT
  account:
    makerCommission: 15
    takerCommission: 15
    balances:
      BTC: 0.0
      USDT: 10000.0

exchangeStrategies:

- on: max
  grid:
    symbol: BTCUSDT
    quantity: 0.001
    gridNumber: 30
    profitSpread: 50.0
    upperPrice: 26800.0
    lowerPrice: 26500.0
    long: true

