persistence:
  json:
    directory: var/data
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

sessions:
  binance:
    exchange: binance
    envVarPrefix: binance

exchangeStrategies:
- on: binance
  irr:
    symbol: BTCBUSD
    interval: 1m
    window: 120
    amount: 5_000.0
    # Draw pnl
    drawGraph: true
    graphPNLPath: "./pnl.png"
    graphCumPNLPath: "./cumpnl.png"

backtest:
  sessions:
    - binance
  startTime: "2022-09-01"
  endTime: "2022-10-04"
  symbols:
    - BTCBUSD
  accounts:
    binance:
      takerFeeRate: 0.0
      balances:
        BUSD: 5_000.0
