---
notifications:
  slack:
    defaultChannel: "bbgo"
    errorChannel: "bbgo-error"
  switches:
    trade: true
    orderUpdate: true
    submitOrder: true


exchangeStrategies:
  - on: max
    marketcap:
      interval: 1m
      quoteCurrency: TWD
      quoteCurrencyWeight: 0%
      baseCurrencies:
        - BTC
        - ETH
        - MATIC
      threshold: 1%
      # max amount to buy or sell per order
      maxAmount: 1_000
      dryRun: true
      queryInterval: 1h
