# usage:
#
#   go run ./cmd/bbgo optimize --config bollmaker_ethusdt.yaml  --optimizer-config optimizer.yaml --debug
#
---
matrix:
- type: iterate
  path: '/exchangeStrategies/0/bollmaker/interval'
  values: ["1m", "5m", "30m"]

- type: range
  path: '/exchangeStrategies/0/bollmaker/amount'
  min: 20.0
  max: 100.0
  step: 20.0

- type: range
  path: '/exchangeStrategies/0/bollmaker/spread'
  min: 0.1%
  max: 0.2%
  step: 0.02%
