---
sessions:
  binance:
    exchange: binance
    envVarPrefix: binance
#    margin: true
#    isolatedMargin: true
#    isolatedMarginSymbol: GMTUSDT
#    futures: true

exchangeStrategies:
- on: binance
  pivotshort:
    symbol: GMTUSDT
    interval: 5m

    pivotLength: 120

    entry:
      quantity: 3000.0
    #      marginOrderSideEffect: borrow

    exit:
      takeProfitPercentage: 25%
      stopLossPercentage: 1%
      lowerShadowRatio: 0.95
#      marginOrderSideEffect: repay


backtest:
  sessions:
  - binance
  startTime: "2022-05-01"
  endTime: "2022-06-03"
  symbols:
  - GMTUSDT
  accounts:
    binance:
      balances:
        GMT: 3010.0
        USDT: 1000.0
