---
sessions:
  binance:
    exchange: binance
    envVarPrefix: binance
    margin: true
    # isolatedMargin: true
    # isolatedMarginSymbol: ETHUSDT

exchangeStrategies:
- on: binance
  pivotshort:
    symbol: ETHUSDT
    interval: 5m
    pivotLength: 200

    # breakLow settings are used for shorting when the current price break the previous low
    breakLow:
      ratio: 0.1%
      quantity: 10.0
      # stopLossPercentage: 1%

    bounceShort:
      quantity: 10.0
      # stopLossPercentage: 1%
      numOfLayers: 10
      layerSpread: 0.1%
      pivotRatio: 0.1%

    exit:
      # roiStopLossPercentage is the stop loss percentage of the position ROI (currently the price change)
      roiStopLossPercentage: 1%

      # roiTakeProfitPercentage is the take profit percentage of the position ROI (currently the price change)
      roiTakeProfitPercentage: 25%

      # lowerShadowRatio is used to force taking profit when the (lower shadow height / low price) > lowerShadowRatio
      lowerShadowRatio: 3%

      marginOrderSideEffect: repay

backtest:
  sessions:
  - binance
  startTime: "2022-04-01"
  endTime: "2022-06-08"
  symbols:
  - ETHUSDT
  accounts:
    binance:
      balances:
        ETH: 10.0
        USDT: 3000.0
