sessions:
  binance:
    exchange: binance
    envVarPrefix: binance
#    futures: true


exchangeStrategies:
- on: binance
  pivotshort:
    symbol: GMTUSDT
    interval: 5m

    pivotLength:  120
    stopLossRatio: 0.5%
    takeProfitRatio: 13%
    shadowTPRatio: 2%

    catBounceRatio: 1%
    quantity: 1200
    numLayers: 4

#    marginOrderSideEffect: borrow

backtest:
  sessions:
    - binance
  startTime: "2022-04-01"
  endTime: "2022-06-03"
  symbols:
    - GMTUSDT
  account:
    binance:
      balances:
        GMT: 5_000.0
        USDT: 5_000.0
