---
exchangeStrategies:
- on: max
  schedule:
    interval: 1m
    symbol: USDTTWD
    side: buy
    quantity: 10

    aboveMovingAverage:
      type: EWMA
      interval: 1h
      window: 99
      side: sell

    belowMovingAverage:
      type: EWMA
      interval: 1h
      window: 99
      side: buy

