---
notifications:
  slack:
    defaultChannel: "dev-bbgo"
    errorChannel: "bbgo-error"
  # object routing rules
  routing:
    trade: "$symbol"
    order: "$symbol"
    submitOrder: "$session" # not supported yet

sessions:
  binance:
    exchange: binance

riskControls:
  # This is the session-based risk controller, which let you configure different risk controller by session.
  sessionBased:
    max:
      orderExecutor:
        bySymbol:
          BTCUSDT:
            basic:
              minQuoteBalance: 100.0
              maxBaseAssetBalance: 3.0
              minBaseAssetBalance: 0.0
              maxOrderAmount: 1000.0

backtest:
  startTime: "2020-09-04"
  endTime: "2020-09-14"
  sessions:
  - binance
  symbols:
  - LINKUSDT
  account:
    binance:
      balances:
        USDT: 10000.0

exchangeStrategies:

- on: binance
  support:
    symbol: LINKUSDT
    interval: 1m
    minVolume: 1_000
    triggerMovingAverage:
      interval: 5m
      window: 99
    longTermMovingAverage:
      interval: 1h
      window: 99

    scaleQuantity:
      byVolume:
        exp:
          domain: [ 1_000, 200_000 ]
          range: [ 0.5, 1.0 ]

    maxBaseAssetBalance: 1000.0
    minQuoteAssetBalance: 2000.0

    trailingStopTarget:
      callbackRatio: 1.5%
      minimumProfitPercentage: 2%

    targets:
    - profitPercentage: 0.02
      quantityPercentage: 0.5
