persistence:
  json:
    directory: var/data
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

sessions:
  binance:
    exchange: binance
    envVarPrefix: binance
#    futures: true

exchangeStrategies:
- on: binance
  trendtrader:
    symbol: BTCBUSD
    trendLine:
      interval: 30m
      pivotRightWindow: 40
      quantity: 1
    exits:
      - trailingStop:
          callbackRate: 1%
          activationRatio: 1%
          closePosition: 100%
          minProfit: 15%
          interval: 1m
          side: buy
      - trailingStop:
          callbackRate: 1%
          activationRatio: 1%
          closePosition: 100%
          minProfit: 15%
          interval: 1m
          side: sell

backtest:
  sessions:
    - binance
  startTime: "2021-01-01"
  endTime: "2022-08-31"
  symbols:
    - BTCBUSD
  accounts:
    binance:
      balances:
        BTC: 1
        BUSD: 50_000.0