---
notifications:
  slack:
    defaultChannel: "dev-bbgo"
    errorChannel: "bbgo-error"

  switches:
    trade: true
    orderUpdate: true
    submitOrder: true

sessions:
  binance:
    exchange: binance
    envVarPrefix: binance
    futures: true

exchangeStrategies:
- on: binance
  funding:
    symbol: ETHUSDT
    quantity: 0.0001
    fundingRate:
      high: 0.01%
    supportDetection:
      - interval: 1m
        movingAverageType: EMA
        movingAverageIntervalWindow:
          interval: 15m
          window: 60
        minVolume: 8_000
