---
notifications:
  slack:
    defaultChannel: "dev-bbgo"
    errorChannel: "bbgo-error"

  switches:
    trade: true
    orderUpdate: true
    submitOrder: true

persistence:
  redis:
    host: 127.0.0.1
    port: 6379
    db: 1

sessions:
  binance:
    exchange: binance
    envVarPrefix: BINANCE

  binance_futures:
    exchange: binance
    envVarPrefix: BINANCE
    futures: true

crossExchangeStrategies:

- xfunding:
    spotSession: binance
    futuresSession: binance_futures
    symbol: ETHUSDT
    leverage: 1.0
    incrementalQuoteQuantity: 11
    quoteInvestment: 110
    shortFundingRate:
      high: 0.000%
      low: -0.01%
    reset: true
