---
notifications:
  slack:
    defaultChannel: "dev-bbgo"
    errorChannel: "bbgo-error"

  # if you want to route channel by symbol
  symbolChannels:
    "^BTC": "btc"
    "^ETH": "eth"

  # if you want to route channel by exchange session
  sessionChannels:
    max: "bbgo-max"
    binance: "bbgo-binance"

  # routing rules
  routing:
    trade: "$symbol"
    order: "$silent"
    submitOrder: "$silent"
    pnL: "bbgo-pnl"

reportPnL:
- averageCostBySymbols:
  - "BTCUSDT"
  - "BNBUSDT"
  of: binance
  when:
  - "@daily"
  - "@hourly"

persistence:
  json:
    directory: var/data
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

sessions:
  max:
    exchange: max
    envVarPrefix: max

  binance:
    exchange: binance
    envVarPrefix: binance

crossExchangeStrategies:

- mobydick:
    symbol: ETHUSDT
    sourceExchange: binance
    makerExchange: max
    updateInterval: 1s

    # disableHedge disables the hedge orders on the source exchange
    # disableHedge: true

    hedgeInterval: 10s

    margin: 0.004
    askMargin: 0.004
    bidMargin: 0.004

    quantity: 0.1
    quantityMultiplier: 2

    # numLayers means how many order we want to place on each side. 3 means we want 3 bid orders and 3 ask orders
    numLayers: 2

    # pips is the fraction numbers between each order. for BTC, 1 pip is 0.1,
    # 0.1 pip is 0.01, here we use 10, so we will get 18000.00, 18001.00 and
    # 18002.00
    pips: 10

    persistence:
      type: redis

